In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr1 = np.zeros((3,3))   ## generating zero matrix

In [5]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr1 + 5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [7]:
arr1 -5

array([[-5., -5., -5.],
       [-5., -5., -5.],
       [-5., -5., -5.]])

In [8]:
np.ones((3,3))     ## generating ones matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.eye(4,4)       ## generating identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.eye(5,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [11]:
print(np.arange(10))    ## generate list of range given 

[0 1 2 3 4 5 6 7 8 9]


In [12]:
np.arange(50).reshape(5,10)      ## used to change the order of matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [13]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
np.linspace(0,10,5)    ## starting pos , ending pos , number of elements we want

## here thry will be equally divide 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.random.rand(10)  ## any number between 0 to 1 

array([0.00817925, 0.07072451, 0.87211428, 0.94286149, 0.42835609,
       0.96623054, 0.50914401, 0.18075457, 0.06898171, 0.88090062])

In [16]:
np.random.randn(10) ## any number with negative also  

array([ 0.23083231,  0.55306409, -1.56386506,  0.40665899,  0.50452035,
        1.40698632,  0.74212925, -0.03129992,  0.07985841,  1.27971519])

In [17]:
np.random.randint(7,10)  ## any integer between start and end [start,end)

7

In [18]:
array = np.array([1,2,3,4,5,6,7,8,9,10])

In [19]:
array.max()

10

In [20]:
array.min()

1

In [21]:
array.argmax()

9

In [22]:
array[5:]

array([ 6,  7,  8,  9, 10])

In [23]:
array[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [24]:
array[5:9] = 20

In [25]:
array

array([ 1,  2,  3,  4,  5, 20, 20, 20, 20, 10])

In [26]:
y = array.copy()

In [27]:
y[1:4] = 90

In [28]:
y

array([ 1, 90, 90, 90,  5, 20, 20, 20, 20, 10])

In [30]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [37]:
arr.diagonal()

array([1, 5, 9])

In [39]:
arr.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [40]:
one = np.array([1,2,3,4,5])
two = np.array([6,7,8,9,10])

In [41]:
one + two

array([ 7,  9, 11, 13, 15])

In [43]:
one * two

array([ 6, 14, 24, 36, 50])

In [44]:
one / two

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [45]:
np.log(one)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [47]:
one_m = np.arange(12).reshape(3,4)
two_m = np.arange(10,22).reshape(4,3)

In [48]:
one_m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
two_m

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [52]:
one_m + two_m.transpose()

array([[10, 14, 18, 22],
       [15, 19, 23, 27],
       [20, 24, 28, 32]])

In [54]:
two_m * one_m

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [55]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [57]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [62]:
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
np.flip(arr)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [68]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])